### ISSUE TITLE
[Suggestion] Booting on 32bit UEFI systems that have a 64bit processor

### ISSUE THREAD

**Issue by Erdragh** [HoloISO/holoiso#132]
I've tried my best to make this work with the current iso, here are the steps I've taken so far, but have not gotten it to work yet, as I don't understand everything about systemd-boot and especially how the `airootfs.sfs` works:

1. used 
    ```
    bsdtar -x --exclude isolinux/ --exclude=EFI/archiso/ --exclude=arch/boot/syslinux/ -f /path/to/.iso -C /path/to/fat32usb
    ```
    to extract the iso, but preventing it from being read-only
2. used the `bootia32.efi` from [EIXreno/archlinux-bootia32](https://github.com/ElXreno/archlinux-bootia32)'s releases and put it into `/path/to/fat32usb/EFI/BOOT/`
3. created my own `bootia32.efi` by modifying the `build.sh` from above mentioned project to reflect how I called the fat32 partition on my usb stick: "HOLOISO" and put it into `/path/to/HOLOISO/EFI/BOOT/`
4. used `grub-install --removable` to install grub with a 32bit efi target to the usb, also `grub-mkstandalone`

If it isn't obvious already, I do not really have a clue what I should do and both grub commands resulted in errors for me.

After step 3 I could boot to grub on my device, but obviously I had the choices from [EIXreno/archlinux-bootia32](https://github.com/ElXreno/archlinux-bootia32)'s grub.cfg. I had hoped that this would allow me to boot HoloISO, as it would resemble archlinux' iso, but afterwards I compared the two iso files, as I was getting errors in grub, and realized the `boot` folder in `/arch/` was missing in HoloISO:
![image](https://user-images.githubusercontent.com/29674493/168805863-3b85f149-31b7-46d0-90fb-5d6d73833484.png)
If I understand things correctly, this is where the files should reside that the bootloader would use to run the system.

So now I have two questions:
- How does this not result in an unbootable iso? I used the exact iso that is open in the screenshot above to create a SteamOS VM with GPU passthrough, so this ISO has to somehow be bootable.
- Would it be possible, maybe by using [EIXreno/archlinux-bootia32](https://github.com/ElXreno/archlinux-bootia32) in one way or another to make HoloISO bootable on systems with a 32bit uefi, but a 64bit processor?

**Comment by ghost** [comment]
Although I do support the request I'm just personal curious: What system do you use that only has a 32bit uefi but is 64bit capable? As far as I'm aware 32bit uefi is only used in embedded fixed systems with a 32bit only cpu. If the hardware itself is 64bit capable it also should have a 64 uefi. I'm not sure if a system booted in 32bit mode can even switch over to 64bit mode - but from a few videos I watched on YT when a bios transitions over to the initial bootloader code the first few instructions are always executed in 16bit real/protected mode and the bootloader then has to switch the cpu to 32bit or 64bit operating mode. But that's only for legacy bios - I think uefi does work quite a bit different hence for uefi one needs a matching efi bootloader.

**Comment by Erdragh** [comment]
I just wanted to play around with SteamOS on an actual device. Pretty much all devices capable of hand held gaming should have 64bit uefi anyways.

This is the device I intended to use:
https://www.odys.de/web/tablet-pc_primewin122in1_en.html
And I have previously had various linux distros installed on it:
- Ubuntu
- Mint
- Fedora
- Arch
- Endeavour

Ubuntu, Mint and Fedora support booting the 64bit os on a 32bit uefi bios by default and for arch and endeavour the steps I described above worked and I could boot and install the OS.

And yes, the CPU is 64bit:
https://www.notebookcheck.net/Intel-Atom-x5-Z8350-SoC.167868.0.html

**Comment by ghost** [comment]
This won't work - at least not with this based-on-deck-recovery-image stuff. When Valve release the full os with a clean install maybe with support for other gpus you may have a chance. But this will not work due to gpu restrictions. The deck is a AMD-only platform with both the cpu and gpu - it ain't gonna work with intel igpu. Aside from that both the intel atom platform as well as intel hd igpu are only very low spec stuff without much 3d power anyway. I doubt you will have much fun even if you get it to run.

**Comment by Erdragh** [comment]
To quote the README:

> Intel GPUs/iGPUs require a Gamescope and MESA downgrade in order to boot into Steam Deck session.

And I wasn't going to use it to actually game - maybe I'd try in home streaming - I just wanted to play around a bit and stumbled upon the fact that HoloISO is missing the /arch/boot folder, and I would like to know why.

But support for more systems without harming anybody is a win in my book, cue this issue/suggestion.

**Comment by BobDev32** [comment]
I don't think it is missing anything, you just not looking int the right place, iso after flashing creates two partitions, one is read only and second is writable, there you will find `/arch/boot`.

I wanted to do same thing but I did it differently:

1. Flash iso to a usb, mount the partition that is writable (it should have 2)
2. Copy bootia32.efi and put it into `/EFI/BOOT/`
3. Create grub.cfg to `/boot/grub/` with menu entry where you add options `add_efi_memmap _IA32_UEFI=1`, not sure if both are needed but it worked for me
4. Boot and do normal install
5. After it is done `arch-chroot` and run `grub-install `
6. You are done

In my case the new release will boot to black screen, the older one was booting to login screen and I could use desktop mode, this new one just shows `Failed to start Jupiter Controller Firmware Update Service`, I cant find old wiki pages where they described two methods to solve intel issues for two versions of handheld, so I don't really know how to solve this.

That said the other way is to copy both partitions from the iso to a folder and merge them, copy bootia and grub then repack it back into iso, then you can use it with ventoys. Like this:
`cd /yourpath/custom_iso && sudo mkisofs -o /yourpath/holoiso32bitefi.iso -b syslinux/isolinux.bin -c syslinux/isolinux.cat -no-emul-boot -boot-load-size 4 -boot-info-table -J -R -V "HOLOISO 32bitEFI" .
`
